---
# tasks file for nginx_config

- name: Install additional packages
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'nginx' ]

- name: Copy nginx configuration in place.
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
